<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="http://jqueryvalidation.org/files/dist/jquery.validate.js"></script>
<script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>

<div class="row">
            <div class="col-md-5">
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title"><strong>Cadastro de Funcionários</strong></h4>
                  <p class="card-category">Preencha seus dados</p>
                </div>
                <div class="card-body">
                  <form >
                    <div class="row">
                      <div class="col-md-3">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Nome</label>
                          <input type="text" name='nome' id='nome' class="form-control">
                        </div>
                      </div>                    
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Sobrenome</label>
                          <input type="text" name='sobrenome' id='sobrenome' class="form-control">
                        </div>
                      </div>
                      <div class="col-md-5">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Email</label>
                          <input type="email" name='email' id='email' class="form-control">
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Telefone</label>
                          <input type="text" name='telefone' id='telefone' class="form-control">
                        </div>
                      </div>                    
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">CPF</label>
                          <input type="text" name='cpf' id='cpf' class="form-control">
                        </div>
                      </div>
                      
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-solid">Data de Nascimento</label>
                          <input type="date" name='dataNascimento' id='dataNascimento' class="form-control">
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Gênero</label>
                          <input type="text" name='genero' id='genero' class="form-control">
                        </div>
                      </div>        
                      
                      <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Estado Civil</label>
                          <input type="text" name='estadoCivil' id='estadoCivil' class="form-control">
                        </div>
                      </div>     

                      <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Função</label>
                          <input type="text" name='funcao' id='funcao' class="form-control">
                        </div>
                      </div>     
                      
                      <div class="col-md-6">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Turno</label>
                          <input type="text" name='turno' id='turno' class="form-control">
                        </div>
                      </div>     

                    
                    <div class="col-md-12">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-solid">Endereço</label>
                          <input type="text" name='endereço' id='endereço' class="form-control">
                        </div>
                      </div>
                    </div>

                    <div class="row">
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Cidade</label>
                          <input type="text" name='cidade' id='cidade' class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">Estado</label>
                          <input type="text" name='estado' id='estado' class="form-control">
                        </div>
                      </div>
                      <div class="col-md-4">
                        <div class="form-group bmd-form-group">
                          <label class="bmd-label-floating">CEP</label>
                          <input type="text" name='cep' id='cep' class="form-control">
                        </div>
                      </div>
                    </div>
                   
                    <button type="submit" class="btn btn-primary pull-right">Cadastrar</button>
                    <div class="clearfix"></div>
                  </form>
                </div>
              </div>
            </div>
            
          </div>